//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tray.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tray.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string btn_apply {
            get {
                return ResourceManager.GetString("btn_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btn_cancel {
            get {
                return ResourceManager.GetString("btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string btn_connect {
            get {
                return ResourceManager.GetString("btn_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string btn_disconnect {
            get {
                return ResourceManager.GetString("btn_disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string btn_login {
            get {
                return ResourceManager.GetString("btn_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error communicating with the service.
        /// </summary>
        public static string ipc_error {
            get {
                return ResourceManager.GetString("ipc_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad response from device.
        /// </summary>
        public static string provider_error_device {
            get {
                return ResourceManager.GetString("provider_error_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logging in.
        /// </summary>
        public static string provider_error_login {
            get {
                return ResourceManager.GetString("provider_error_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device not found.
        /// </summary>
        public static string provider_error_notfound {
            get {
                return ResourceManager.GetString("provider_error_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        public static string provider_error_unknown {
            get {
                return ResourceManager.GetString("provider_error_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect PIN.
        /// </summary>
        public static string provider_error_userpin {
            get {
                return ResourceManager.GetString("provider_error_userpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in successfully.
        /// </summary>
        public static string provider_logged_in {
            get {
                return ResourceManager.GetString("provider_logged_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for login.
        /// </summary>
        public static string provider_wait_config {
            get {
                return ResourceManager.GetString("provider_wait_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string wc_device {
            get {
                return ResourceManager.GetString("wc_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        public static string wc_pin {
            get {
                return ResourceManager.GetString("wc_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SElink: Device.
        /// </summary>
        public static string wc_title {
            get {
                return ResourceManager.GetString("wc_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your user pin.
        /// </summary>
        public static string wl_prompt {
            get {
                return ResourceManager.GetString("wl_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SElink: Login.
        /// </summary>
        public static string wl_title {
            get {
                return ResourceManager.GetString("wl_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow,Block,Encrypt.
        /// </summary>
        public static string wr_actions {
            get {
                return ResourceManager.GetString("wr_actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New rules applied.
        /// </summary>
        public static string wr_apply_ok {
            get {
                return ResourceManager.GetString("wr_apply_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string wr_col_action {
            get {
                return ResourceManager.GetString("wr_col_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination IP.
        /// </summary>
        public static string wr_col_address {
            get {
                return ResourceManager.GetString("wr_col_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string wr_col_description {
            get {
                return ResourceManager.GetString("wr_col_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable Path.
        /// </summary>
        public static string wr_col_exepath {
            get {
                return ResourceManager.GetString("wr_col_exepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key ID.
        /// </summary>
        public static string wr_col_keyid {
            get {
                return ResourceManager.GetString("wr_col_keyid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Port.
        /// </summary>
        public static string wr_col_portfirst {
            get {
                return ResourceManager.GetString("wr_col_portfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Port.
        /// </summary>
        public static string wr_col_portlast {
            get {
                return ResourceManager.GetString("wr_col_portlast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string wr_delete {
            get {
                return ResourceManager.GetString("wr_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix all errors before applying the new rules.
        /// </summary>
        public static string wr_grid_inval {
            get {
                return ResourceManager.GetString("wr_grid_inval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert after.
        /// </summary>
        public static string wr_insert_after {
            get {
                return ResourceManager.GetString("wr_insert_after", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert before.
        /// </summary>
        public static string wr_insert_before {
            get {
                return ResourceManager.GetString("wr_insert_before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masked rules.
        /// </summary>
        public static string wr_masking_msgbox_title {
            get {
                return ResourceManager.GetString("wr_masking_msgbox_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{1}&quot; (Rule #{0}) is masked by &quot;{3}&quot; (Rule #{2}).
        /// </summary>
        public static string wr_masking_warn {
            get {
                return ResourceManager.GetString("wr_masking_warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and {0} more....
        /// </summary>
        public static string wr_masking_warn_more {
            get {
                return ResourceManager.GetString("wr_masking_warn_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string wr_prefix_new {
            get {
                return ResourceManager.GetString("wr_prefix_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SElink: Filter Rules.
        /// </summary>
        public static string wr_title {
            get {
                return ResourceManager.GetString("wr_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid IPv4 or IPv6 address, or leave empty.
        /// </summary>
        public static string wr_val_err_address_inval {
            get {
                return ResourceManager.GetString("wr_val_err_address_inval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description length cannot exceed 64 characters.
        /// </summary>
        public static string wr_val_err_description_inval {
            get {
                return ResourceManager.GetString("wr_val_err_description_inval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid Key ID.
        /// </summary>
        public static string wr_val_err_keyid_inval {
            get {
                return ResourceManager.GetString("wr_val_err_keyid_inval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key ID should be empty for this action.
        /// </summary>
        public static string wr_val_err_keyid_should_be_empty {
            get {
                return ResourceManager.GetString("wr_val_err_keyid_should_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid port range, or leave both fields empty.
        /// </summary>
        public static string wr_val_err_portrange_inval {
            get {
                return ResourceManager.GetString("wr_val_err_portrange_inval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SElink.
        /// </summary>
        public static string wt_balloon_title {
            get {
                return ResourceManager.GetString("wt_balloon_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string wt_device {
            get {
                return ResourceManager.GetString("wt_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Rules.
        /// </summary>
        public static string wt_filter_rules {
            get {
                return ResourceManager.GetString("wt_filter_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string wt_quit {
            get {
                return ResourceManager.GetString("wt_quit", resourceCulture);
            }
        }
    }
}
